### ISSUE TITLE
Question about the result in your paper being different from the original paper

### ISSUE THREAD

**Issue by yuanczx** [rookiehb/DisMAE#3]
Thank you for your nice work. I am confused that in your paper, the results cited from previous UDG work differ from those reported in the original paper.

**Comment by rookiehb** [comment]
Hi, thanks for your interest in our work.

We have mentioned the implementation difference in our experimental setup. Since our network is highly associated with ViT architecture, we choose to replace all the ResNet-based baselines with the backbone of ViT and rerun the experiments, just for a fair comparison. That is the reason why our results differ from the original paper, DARLING.

Our results are also different from paper DiMAE/CycleMAE for the reasons below. If you look through their experimental setups carefully, you can find they choose to initialize their ViT backbone with checkpoints pre-trained on the ImageNet. That is not consistent with the original setup in the DARLING paper. Thus, instead, in our reproduction, we follow the original setup and choose not to load any checkpoints pre-trained on ImageNet. Every baseline and our framework all follow the procedure of randomly initializing the weights, pre-training on the DomainNet, and finally fine-tuning on the DomainNet. We also did a sanity check to reproduce the results of CycleMAE loading checkpoints pre-trained on the ImageNet. The results are very close to those reported in their CycleMAE paper.

**Comment by yuanczx** [comment]
Thank you for the detailed explanation.
